version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password19
      - POSTGRES_USER=bakery
      - POSTGRES_DB=test_bakery_db
    

  postgres-esp:
      image: postgres:latest
      container_name: postgres_db
      ports:
        - "5433:5432" 
      environment:
        POSTGRES_DB: sensor_db
        POSTGRES_USER: bakery
        POSTGRES_PASSWORD: password19
      volumes:
        - ./postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSockets port (optional, for MQTT over WebSockets)
    volumes:
      - ./mosquitto/config:/mosquitto/config  # Configurations
      - ./mosquitto/data:/mosquitto/data      # Persistent data
      - ./mosquitto/log:/mosquitto/log        # Logs
    networks:
      - mqtt_network
    restart: unless-stopped

networks:
  mqtt_network:
    driver: bridge

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=bakery
  #     - RABBITMQ_DEFAULT_PASS=password19
  #     - deprecated_features.permit.transient_nonexcl_queues = false
